### ISSUE TITLE
AUTH_LDAP_FIND_GROUP_PERMS setting unclear

### ISSUE THREAD

**Issue by vanschelven** [django-auth-ldap/django-auth-ldap#255]
It is not clear (to me at least) what `AUTH_LDAP_FIND_GROUP_PERMS` does exactly. From the documentation:

> If True, LDAPBackend will furnish group permissions based on the LDAP groups the authenticated user belongs to.

There is also the following hint in the README, which is already a bit more clear to me:

> Use LDAP group membership to calculate group permissions.

When reading the source code, my understanding is

> If True, the LDAPBackend use group membership to calculate group permissions, that is: if a user is a member a given LDAP group, the permissions of the Django group with the same name will be given to that user.

If this understanding is correct, I'm still a bit puzzled:

* Isn't this the default behavior in Django, i.e. why is there a separate (default False) option for this? 
* What is the relationship with `AUTH_LDAP_MIRROR_GROUPS`, i.e. wouldn't setting that setting to True imply the behavior regardless of the value for `AUTH_LDAP_USER_FLAGS_BY_GROUP`?

**Comment by francoisfreitag** [comment]
> [`AUTH_LDAP_FIND_GROUP_PERMS`=False]
> Isn't this the default behavior in Django, i.e. why is there a separate (default False) option for this?

The default to `False` is probably to prevent giving permissions to users accidentally. It’s much safer to deny by default, unless specified otherwise.

**`AUTH_LDAP_FIND_GROUP_PERMS`**

> If True, the LDAPBackend use group membership to calculate group permissions, that is: if a user is a member a given LDAP group, the permissions of the Django group with the same name will be given to that user.

:+1: Looks correct to me.

Note that this does not grant users the membership to the Django groups. That’s the main difference with `AUTH_LDAP_MIRROR_GROUPS`. For example, your application logic may rely on group membership for custom permission / viewability checks that are different from the Django permission system.

`AUTH_LDAP_FIND_GROUP_PERMS` calculates the permissions from the LDAP, which means the LDAP group permission is the source of truth. With `AUTH_LDAP_MIRROR_GROUPS`, the Django database duplicates the LDAP group membership.
If you have multiple backends, `AUTH_LDAP_FIND_GROUP_PERMS` will give permissions to users authenticated through LDAP, but not other authentication backends.

Another subtle difference is that `_LDAPUser.get_group_permissions()` will return the permissions regardless if the user `is_active` (versus Django https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.backends.ModelBackend.get_group_permissions).

**`AUTH_LDAP_MIRROR_GROUPS`**

The assigns groups to users. Group membership is stored in the Django database, so users authenticating with e.g. the ModelBackend have the permissions from their groups. The permission remain until users authenticate using the LDAP again, which syncs the user’s group membership.

**`AUTH_LDAP_USER_FLAGS_BY_GROUP`**

That is just to populate boolean attributes on the user model based on group membership.
https://github.com/django-auth-ldap/django-auth-ldap/blob/805d853f9844846a1ad700eea1721dc6b47cc3d5/README.rst#L124-L128

Once the attribute (flag) is populated, the membership information is not retained.

**Comment by vanschelven** [comment]
Thanks very much for the very clear explanation! For me personally this closes the issue; I'm leaving it up to you to close it if/when you update the documentation (or to close it without updating the documentation if you so prefer).

**Comment by francoisfreitag** [comment]
Thanks for reporting back!
I’ll try to clarify the docs in the upcoming weeks, keeping the issue around for that purpose. If you feel like it, PRs are also very welcome. :slightly_smiling_face:

**Comment by francoisfreitag** [comment]
Hi @vanschelven,

I opened #265 in an attempt to clarify both settings. A review would be much appreciated!

**Comment by vanschelven** [comment]
> A review would be much appreciated!

Done, looks good to me!

**Comment by francoisfreitag** [comment]
Thanks!
