### ISSUE TITLE
LDAPS / TLS Connection Timeout

### ISSUE THREAD

**Issue by sarabrajsingh** [django-auth-ldap/django-auth-ldap#287]
Hi,

I have a customer environment that has a Microsoft AD LDS server setup, and we are using the `django-auth-ldap` to interact with it. We are experiencing the AD LDS server issusing `TCP RST` calls back to our client after TLS handshake is established. We believe that the issue originates from the recent security changes on the AD LDS server; specifically TLS connection timeouts. Please refer to the article below for more precise details:

https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/ldap-kerberos-server-reset-tcp-sessions

I tried playing around with the `OPT_X_KEEPALIVE_*` options to no avail. I was wondering which options could be used, or if a `unbind` method could be exposed on the `django.auth_ldap.backend` module or in the `_LDAPUser` class so that we can manually terminate any stale or idleing connections.

**Comment by francoisfreitag** [comment]
Hi,

Thanks for the summary.
The underlying connection can be accessed on an `_LDAPUser` through the `_connection` attribute. I suppose you could call `unbind_s()` on the connection to terminate it, but you should make sure not to access attributes or group membership info from the LDAP after the connection has been unbound. The library keeps the connection around after authentication to load more info from the LDAP server in subsequent requests without re-establishing a connection.

> I tried playing around with the `OPT_X_KEEPALIVE_*`

If the issue is indeed “Incorrect idle session monitoring”, then my guess is the keep alive options won’t help, as the [docs specify](https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/ldap-kerberos-server-reset-tcp-sessions):

> newly created sessions may be disconnected immediately by the server sporadically.

The connection is currently not unbound explicitly. IIUC, python-ldap [unbinds](https://github.com/python-ldap/python-ldap/blob/47975ee75c84748abfb8bb7456d5cc0a34cfce41/Modules/LDAPObject.c#L44) when the object is destructed.

Are you looking to implement a sort of retry mechanism?
---

Somewhat related, https://github.com/django-auth-ldap/django-auth-ldap/pull/174 offers to unbind immediately after each connection to the LDAP, which is not compatible with current usage (see the broken tests), and probably not desirable in this state, as multiple connections to the LDAP would need to be opened over the course of one request.

**Comment by sarabrajsingh** [comment]
@francoisfreitag thanks for the reply. #174 does look interesting and would be worth a try on my end, if it lands.

as for the retry - i am making an attempt of implementing that on my own within the application. A non-authenticated user returns a `None`-type back to the caller and I can add a handle in the event of a `None`-type. My question is, do you think that will resolve the `TCP RST` issue from the server? I guess it would be hard to say without knowing how many TCP sessions against the LDAP server my application is making.

**Comment by francoisfreitag** [comment]
> do you think that will resolve the TCP RST issue from the server?

IIUC, the `TCP RST` come from a flaw on the server side, so I don’t think changing anything on the client side will solve your issue. The retry mechanism is probably an efficient mitigation though.

**Comment by sarabrajsingh** [comment]
thanks for the advice @francoisfreitag. i think we can safely close this issue, #174 will be a nice feature to extend this retry functionality when it gets merged in.
