### ISSUE TITLE
Malicious login attempt with malicious string will log an error

### ISSUE THREAD

**Issue by mogoh** [django-auth-ldap/django-auth-ldap#306]
Hello,

today, my Django instance ~~crashed~~ logged an error with this login attempt:

```
search_s('ou=users,dc=***censored***,dc=de', 2, '(uid=0"XOR\28if\28now\28\29=sysdate\28\29,sleep\2815\29,0\29\29XOR"Z)') raised OPERATIONS_ERROR({'msgtype': 101, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': 'LDAP Error 1 : com.octetstring.vde.util.DirectoryException: LDAP Error 19 : Constraint Violation'})
```

~~Everything worked well for the last couple of month, but a Django instance should of course not crash because of a malicious login attempt.~~
See update below.
Now the question is, should I somewhere clean/sanitize the username and password, or should django-auth-ldap do that?

## My login view 

is similar to this: https://docs.djangoproject.com/en/3.2/topics/auth/default/#how-to-log-a-user-in-1

## My LDAP config is

```
# Authentication and LDAP Settings
AUTHENTICATION_BACKENDS = [
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AUTH_LDAP_SERVER_URI = 'ldaps://***censored***:636'

AUTH_LDAP_BIND_DN = 'cn=***censored***,ou=***censored***,dc=***censored***,dc=de'
AUTH_LDAP_BIND_PASSWORD = get_secret("LDAP_BIND_PASSWORD")

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    'ou=users,dc=***censored***,dc=de',
    ldap.SCOPE_SUBTREE,
    '(uid=%(user)s)',
)

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    'cn=***censored***,ou=groups,dc=***censored***,dc=de',
    ldap.SCOPE_SUBTREE,
    '(objectClass=groupOfUniqueNames)',
)

AUTH_LDAP_GROUP_TYPE = GroupOfUniqueNamesType()

AUTH_LDAP_REQUIRE_GROUP = 'cn=***censored***,ou=groups,dc=***censored***,dc=de'

AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600
```

## I am using

Django==3.2.13
django-auth-ldap==4.0.0

**Comment by francoisfreitag** [comment]
That’s because authentication failures (not errors) are caught by the library and turned into `AuthenticationFailed` errors, that are [logged at the debug level](https://github.com/django-auth-ldap/django-auth-ldap/blob/8c2eb6a4788f6825fa84934c5990b3d72759f2d2/django_auth_ldap/backend.py#L353-L354), and debug logs are mostly ignored unless you’ve setup your environment to see them.

A failed authentication happens when the library did its work as expected, but e.g. the user credentials did not match, so the library has nothing of interest to report to developers.
An `LDAPError` however means the library queried the LDAP in an inappropriate manner. The ldap library raises an exception, which django-auth-ldap catches and logs to avoid users to have to deal with that exception. Because the library could not do its work as expected, the issue needs to be reported, as it reveals developer errors or malicious user actions.

**Comment by mogoh** [comment]
OK, interesting.
I would not call this an error, because it is working as intended.
A malicious login attempt gets refused.
But I don't know, how error propagation between OpenLDAP and Django Auth LDAP works and I guess LDAPError has to be mapped somehow on Django error level.

What I found so confusing is that:

- Name: `foo` PW: `bar` : no error
- Name: `fdsfdsafdsafdasfdsa` PW: `fdsafdasfdsaf` : no error
- Name: `(=),` PW: `bar` : no error
- Name: `if(now()=sysdate(),sleep(15),0` PW: `bar` : no error
- Name: `if(now()=sysdate(),sleep(15),0)` PW: `bar` : **error**

So there must be somewhere a logic that detects the malicious attempt.
I did not expect that.
But if that is how it is, then fine.

Thanks again for your help.
