### ISSUE TITLE
Allow to raise LDAP errors via settings

### ISSUE THREAD

**Issue by xi** [django-auth-ldap/django-auth-ldap#380]
I use django-auth-ldap in combination with django-axes, which locks out users after too many failed login attempts. I recently had a situation where the LDAP server was not reachable. Users who tried to log in during that time were locked out by django-axes, which made the situation even worse. Even after the LDAP server was reachable again, many users were still unable to log in.

As far as I understand, a fix would be to use the `ldap_error` signal to raise exceptions if the connection fails:

```python
from django_auth_ldap.backend import ldap_error
from django.dispatch import receiver

@receiver(ldap_error)
def raise_ldap_error(sender, user, request, exception, **kwargs):
    raise exception
```

However, I am using a third party software, so I can only change the settings. If I try to add this signal handler in the settings, I get the following error:

```
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Note that it wouldn't work to add the signal handler to the software itself, because it can be combined with different authentication backends. This handler only makes sense for my specific setup.

So my request is to add a boolean setting (e.g. `AUTH_LDAP_RAISE_LDAP_ERRORS`). I would also be fine with more flexible solutions, as long as they can be used in the settings, without modifying application code.

**Comment by francoisfreitag** [comment]
Thanks for the description and PR :+1:.

I’m not thrilled by adding a new setting to the app, it would be the 27th, and it seems a fairly niche use case, where developers do not control the code.

You would like a way to indicate to django-axes that the issue wasn’t a failed login attempt from the user but a technical issue. Which is why you’ve suggested letting the exception bubble up. I’m unclear what would be responsible for catching the exception if you do not have control on the code? Would a 500 be displayed to users?

> I am using a third party software, so I can only change the settings.

Can you give a bit more details on that? Is there no way for you to install a django app, hook custom Python modules, or extend the third party software beyond the settings?

**Comment by xi** [comment]
> Would a 500 be displayed to users?

Yes. The 500 template tells users that there are technical issues. And the logging setup takes care of sending a notification to admins. All of this is exactly what I want if the LDAP server is not available.

Of course, ideally the LDAP server should never go down. But if it does, I want to know quickly.

I think the only case where I wouldn't want to get an exception is if I have multiple backends and the user might be able to authenticate with a different backend. I guess that is a fairly niche use case itself. So I would absolutely be fine with changing the default instead of adding a setting. But that would break backwards compatibility.

> I am using a third party software, so I can only change the settings.

I probably could create a custom django app and somehow mount that into the container. But that is a very complex solution for something that should be simple. All other aspects of the authentication process (e.g. which backends are used) can be controlled in the settings.

The only other workaround I can think of is to convince the maintainers of any application that might be used with django-auth-ldap to add this setting into their code. That would just be redundant work though.

**Comment by francoisfreitag** [comment]
> So I would absolutely be fine with changing the default instead of adding a setting. But that would break backwards compatibility.

If we were to make that change, it would become hard for other developers to handle an `LdapError` in the middle of `django.contrib.auth.authenticate`. They would need to subclass the backend to catch the exception and keep going. And if they cannot change the application code, it leaves them in the same situation as yours currently.

> I probably could create a custom django app and somehow mount that into the container. But that is a very complex solution for something that should be simple.

The simple way is to register a signal handler. It’s only becoming complex because the third party software does not give you enough control. It might benefit that third party software to allow developers to extend behavior with code (plugins/custom apps).

Otherwise, I believe a simple workaround for your issue is to monkey patch with `unittest.mock`. Untested, but should work in your `settings.py`:
```python
from unittest import mock

def raise_error(sender, context, user, request, exception):
    raise exception

mock.patch("django_auth_ldap.backend._report_error", raise_error).start()
```

The following test passes:
```python
from unittest import mock

import ldap
from django.contrib.auth import authenticate
from django.test import SimpleTestCase, override_settings


class ReportErrorMockTest(SimpleTestCase):
    @override_settings(
        AUTH_LDAP_SERVER_URI="invalid",
        AUTH_LDAP_USER_DN_TEMPLATE="%(user)s@people.test",
    )
    def test_mocking(self):
        def raise_error(sender, context, user, request, exception):
            raise exception

        with mock.patch("django_auth_ldap.backend._report_error", raise_error):
            with self.assertRaisesMessage(ldap.LDAPError, "Error"):
                authenticate(username="alice", password="password")

```

That avoids introducing a new setting for what seems to be a pretty niche use case. If there is strong support for that setting, we can reconsider.

**Comment by xi** [comment]
> The simple way is to register a signal handler. It’s only becoming complex because the third party software does not give you enough control. It might benefit that third party software to allow developers to extend behavior with code (plugins/custom apps).

I really disagree on this. Django allows you to configure authentication in the settings. You can use any existing django application and combine it with django-auth-ldap without modifying the code. It is not the third party software that does not give me enough control. It is django-auth-ldap that doesn''t play nice with the django ecosystem here.

I get that you want to avoid changing the default behavior or adding a new setting. Thanks for proposing the monkey patch. I hadn't thought of that. It is probably workable, even though it is brittle.

> If there is strong support for that setting, we can reconsider.

Fine with me.

**Comment by xi** [comment]
I finally got around to test the monkey patch and it has the same issue as registering signals:

```
AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by francoisfreitag** [comment]
If you can try it out, #382 should solve your issue.

**Comment by francoisfreitag** [comment]
Thanks, I’ll merge and release a new version tomorrow.
